config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'pages#home'

  resources :tasks, only: [:index, :create, :new, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :colocs do
    get '/join', to: 'colocs#join'
  end

  resources :carotte_cards, only: [:index]
  resources :user_tasks, only: [:edit, :update] do
    patch 'mark_as_done', on: :member
    post 'carotte', on: :member
    get 'carotte_validation', on: :member
  end

  resources 'shop', controller: 'fun_cards', only: [:index, :show] do
    resources :consommations, only: :create
  end
  # get 'shop', to: 'fun_cards#index'
  # get 'shop/:id', to: 'fun_cards#show', as: :shop_fun_card
  # post 'shop/:id/buy', to: 'consommations#buy', as: :buy_fun_card

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :coloc

  has_many :user_tasks, dependent: :destroy
  has_one  :current_user_task, -> { current_week }, class_name: 'UserTask'

  validates :name, presence: true
  validates :description, presence: true
  validates :points, inclusion: { in: (1..200) }
  validates :points, presence: true
  # validates :carotte_card_description, presence: true
  # validates :carotte_card_points, presence: true
  # validates :carotte_card_points, inclusion: { in: (1..200) }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @task = Task.find(params[:id])
    @coloc = current_user.coloc
    @tasks_to_do = UserTask.where(user: current_user, status: false)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.coloc = current_coloc
    if @task.save!
      redirect_to tasks_path
    else
      render :new
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :points, :photo)
  end
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.input :image, as: :file %>

  <%= f.submit "Submit proof" %>
<% end %>

app/views/tasks/new.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :points %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/show.html.erb
  <h4 class="title"> TU VALIDES OU TU CAROTTES ?</h4>

<div class="container">

  <div class="show_task_image">
    <p><%= image_tag @task.image, alt: 'task_image', class: 'task_image_large'%></p>
  </div>

  <p class="show_task_name"><%= @task.name %></p>
  <p class="show_task_description"><%= "\"#{@task.description}\"" %></p>

    <div class="submit_btn_show">

    <div class="btn_and_description">
      <div class="icon_check">
        <%= link_to icon('fas', 'check'), edit_user_task_path(@task.current_user_task), class: "btn-check"%>
        <p class="show_task_points"> + <%= @task.points %> <%= image_tag ('carotte_sans_rond.png'), class:"carot-show" %></p>
      </div>
      <p class="btn_description">Je valide<br>ma tâche</p>
    </div>

    <div class="btn_and_description">
      <div class="icon_carot">
        <%= link_to tasks_path, "data-toggle" => "modal", 'data-target' => '#exampleModal', class:"btn-carot" do %>
          <i class="fas fa-times"></i>
        <% end %>
        <p class="show_task_points last"> - <%= @task.carotte_card_points %> <%= image_tag ('carotte_sans_rond.png'), class:"carot-show" %> </p>
      </div>
      <p class="btn_description">Je l'affecte à<br>un coloc</p>
    </div>

    </div>

    <% if current_user.current_points >= @task.carotte_card_points %>
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-body text-center">
              Je <%= image_tag 'carotte.png', alt: 'task_image', class: 'carot_modal' %> mon coloc !
            </div>
            <div class="modal-footer text justify-content-around">
              <button type="button" class="close fa-3x" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true", class="text-danger">&times;</span>
              </button>
              <%= link_to icon('fas', 'check'), carotte_user_task_path(@task.current_user_task), method: :post, class:'btn-check-modal text-success fa-2x'%>
            </div>
          </div>
        </div>
      </div>
      <% else %>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body text-center">
                Mince, il me manque encore des <%= image_tag 'carotte.png', alt: 'task_image', class: 'carot_modal' %>
              </div>
              <div class="modal-footer text justify-content-center">
                <button type="button" class="close fa-3x" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true", class="text-danger">&times;</span>
                </button>
              </div>
            </div>
          </div>
        </div>
    <% end  %>
</div>