config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'pages#home'

  resources :tasks, only: [:index, :create, :new, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :colocs do
    get '/join', to: 'colocs#join'
  end

  resources :carotte_cards, only: [:index]
  resources :user_tasks, only: [:edit, :update] do
    patch 'mark_as_done', on: :member
    post 'carotte', on: :member
    get 'carotte_validation', on: :member
  end

  resources 'shop', controller: 'fun_cards', only: [:index, :show] do
    resources :consommations, only: :create
  end
  # get 'shop', to: 'fun_cards#index'
  # get 'shop/:id', to: 'fun_cards#show', as: :shop_fun_card
  # post 'shop/:id/buy', to: 'consommations#buy', as: :buy_fun_card

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_tabbar.html.erb
<% display_animation = @display_animation || false  %>

<div class="tab-bar">
  <div class="tab_elements">
    <%= link_to image_tag('coloc.png'), root_path, class:"icon"%>
    <p>Tach'Board</p>
  </div>

  <div class="tab_elements">
      <div>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="current-points">
          <div>
            <%= image_tag 'carotte.png', alt: 'task_image', class: 'carot_tabbar'%>
          </div>

          <div id="my_carrots" data-end-number="<%= current_user.current_points %>">
            <%= params[:old_points] || current_user.current_points %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
    <div class="tab_elements">
    <div class="tab_image">
      <%= link_to image_tag('shop.png'), shop_index_path, class:"icon"%>
    </div>
    <p>Shop</p>
  </div>
</div>