config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'pages#home'

  resources :tasks, only: [:index, :create, :new, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :colocs do
    get '/join', to: 'colocs#join'
  end

  resources :carotte_cards, only: [:index]
  resources :user_tasks, only: [:edit, :update] do
    patch 'mark_as_done', on: :member
    post 'carotte', on: :member
    get 'carotte_validation', on: :member
  end

  resources 'shop', controller: 'fun_cards', only: [:index, :show] do
    resources :consommations, only: :create
  end
  # get 'shop', to: 'fun_cards#index'
  # get 'shop/:id', to: 'fun_cards#show', as: :shop_fun_card
  # post 'shop/:id/buy', to: 'consommations#buy', as: :buy_fun_card

end

app/models/coloc.rb
class Coloc < ApplicationRecord
  has_many :users
  has_many :tasks

  has_many :consommations, through: :users
  
  validates :name, presence: true
end

app/controllers/colocs_controller.rb
class ColocsController < ApplicationController
  def new
    @coloc = Coloc.new
  end

  def create
    @coloc = Coloc.new(coloc_params)

    if @coloc.save!
      current_user.update(coloc_id: @coloc.id)
    else
      render :new
    end
  end

  def join
    current_user.update(coloc: @coloc)
    redirect_to root_path
  end

  private

  def set_coloc
    @coloc = Coloc.find(params[:id])
  end

  def coloc_params
    params.require(:coloc).permit(:name)
  end
end

app/views/colocs/create.html.erb
  <p>Invite your coloc :</p>
  <p><%= coloc_join_url(@coloc) %></p>

   <%= link_to 'Go to home', root_path , class:"btn-ghost-small"%>

app/views/colocs/new.html.erb
<%= simple_form_for(@coloc) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Choose a name" %>
  </div>  
  <div>
      <%= f.submit class:'btn-submit' %>
  </div>
<% end %>

app/views/colocs/show.html.erb
w<h1>Your coloc</h1>
<h2>Stats</h2>

   <%= link_to 'Go to home', root_path , class:"btn-ghost-small"%>