config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  root to: 'pages#home'

  resources :tasks, only: [:index, :create, :new, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :colocs do
    get '/join', to: 'colocs#join'
  end

  resources :carotte_cards, only: [:index]
  resources :user_tasks, only: [:edit, :update] do
    patch 'mark_as_done', on: :member
    post 'carotte', on: :member
    get 'carotte_validation', on: :member
  end

  resources 'shop', controller: 'fun_cards', only: [:index, :show] do
    resources :consommations, only: :create
  end
  # get 'shop', to: 'fun_cards#index'
  # get 'shop/:id', to: 'fun_cards#show', as: :shop_fun_card
  # post 'shop/:id/buy', to: 'consommations#buy', as: :buy_fun_card

end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task

  scope :done, -> { where(status: true) }
  scope :to_do, -> { where(status: false) }

  scope :current_week, -> { where(week_on: Date.today.beginning_of_week) }
  scope :next_week, -> { where(week_on: Date.today.next_week) }

  validates :week_on, presence: true
  validates :week_on, uniqueness: { scope: :task }
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :set_user_vars, only: [:mark_as_done, :carotte, :carotte_validation]

  def edit
    @user_task = UserTask.find(params[:id])
  end

  def update
    @user_task = UserTask.find(params[:id])
  end

  def mark_as_done
    @user_task.update(status: true)
    old_points = @user.current_points
    sum_points = @user.current_points + @task.points
    @user.update(current_points: sum_points)
    redirect_to root_path(old_points: old_points)
  end

  def carotte
    array_user = []
    array_user << @user
    if @user.current_points >= @task.carotte_card_points
      other_users = current_coloc.users - array_user
      carotted_user = other_users.sample
      @user_task.update(user: carotted_user)

      carotted_points = @user.current_points - @task.carotte_card_points
      carotted_total_points = @user.total_points - @task.carotte_card_points
      old_points = @user.current_points
      @user.update(current_points: carotted_points, total_points: carotted_total_points)

      redirect_to carotte_validation_user_task_path(username: carotted_user.name, old_points: old_points)
    end
  end

  def carotte_validation
    @carotted_user = User.where(name: params[:username])
    @display_animation = true
  end

  private

  def set_user_vars
    @user_task = UserTask.find(params[:id])
    @task = @user_task.task
    @user = current_user
  end

  # def dreams_params
  #   params.require(:user_tasks).permit(:status)
  # end
end

app/views/user_tasks/_form.html.erb
<%= form_for(@user_tasks) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.input :image, as: :file %>

  <%= f.submit "Submit proof" %>
<% end %>

app/views/user_tasks/carotte_validation.erb
<div class="container">

  <div class="carott_card" >
    <h4 class="carotted_title"> <strong> Bravo ! <br> Tu as carotté :</strong></h4>
      <div class="carotted_avatar" id="carot_card_select">
        <p><%= image_tag @carotted_user.first.avatar, class: 'avatar-x-large' %></p>
      </div>
     <h4 class="carotted_user_name"><%= @carotted_user.first.name %></h4>
  </div>

   <div>

     <%= link_to '> Retour au Tach\'Board', root_path, class:"btn_coloc" %>

   </div>

</div>

app/views/user_tasks/edit.html.erb
<h4 class="title">VALIDE TA TÂCHE</h4>

<div class="container-photo">
  <div class="tasks_done">
    <div class="align_items">
      <%= simple_form_for(@user_task, url: mark_as_done_user_task_path(@user_task)) do |f| %>

        <div class="form-group file optional user_task_photo" id="input_photo">
          <label class="file optional" for="user_task_photo">
            <%= image_tag "camera-02.png", class: "preview_img camera_img" %>
          </label>
          <p class="upload_photo_text">PROUVE LE À TES COLOCS</p>
          <input class="form-control-file file optional" type="file" name="user_task[photo]" id="user_task_photo">
        </div>

        <input class="input_btn" type="submit" name="commit" value="Je valide !">
      <% end %>
      <%= link_to "> Revenir à la tâche", task_path(@user_task.task), class: "back_btn" %>
    </div>
  </div>
</div>